// Generated by CoffeeScript 1.6.3
var app;

app = app || {};

(function() {
  "use strict";
  var MonitorRouter;
  MonitorRouter = Backbone.Router.extend({
    routes: {
      "metric/:name": "metricsShow"
    },
    metricsShow: function(name) {
      var item;
      item = new app.Metric({
        name: name
      });
      app.metrics.add(item);
      return item.save();
    }
  });
  app.MonitorRouter = new MonitorRouter();
  return Backbone.history.start();
})();
