// Generated by CoffeeScript 1.6.3
(function() {
  var ENTER_KEY, app;

  app = app || {};

  ENTER_KEY = 13;

  $(function() {
    "use strict";
    return new app.MonitorView();
  });

}).call(this);
