// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = app || {};

  (function($) {
    "use strict";
    return app.HostMetricView = Backbone.View.extend({
      tagName: "li",
      template: _.template($("#hostmetric-template").html()),
      initialize: function() {
        return $(".search-query").quicksearch("ul li");
      },
      render: function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this;
      }
    });
  })(jQuery);

}).call(this);
