// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = app || {};

  (function($) {
    "use strict";
    return app.MetricView = Backbone.View.extend({});
  })(jQuery);

}).call(this);
