// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = app || {};

  (function() {
    "use strict";
    var Metrics;
    Metrics = Backbone.Collection.extend({
      model: app.Metric,
      url_api: "/api/v1/metric?metrics=",
      localStorage: new Backbone.LocalStorage("metrics-backbone")
    });
    return app.metrics = new Metrics();
  })();

}).call(this);
